import { existsSync, readFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { test } from 'vitest';
// @ts-expect-error The runtime module is generated by `npm run build` before Vitest runs.
import { dump } from '../../dist/index.mjs';
import type {
  ChibiccDumperAstOnlyResult,
  ChibiccDumperDumpResult,
  ChibiccDumperFullDumpResult,
  ChibiccDumperFunctionObject,
  ChibiccDumperHeaderComment,
  ChibiccDumperKeywordToken,
  ChibiccDumperLocalObject,
  ChibiccDumperMember,
  ChibiccDumperNode,
  ChibiccDumperNodeKind,
  ChibiccDumperNodeOfKind,
  ChibiccDumperObject,
  ChibiccDumperProgram,
  ChibiccDumperRelocation,
  ChibiccDumperScope,
  ChibiccDumperTag,
  ChibiccDumperTokenKind,
  ChibiccDumperTokenOfKind,
  ChibiccDumperTokenRef,
  ChibiccDumperTokensOnlyResult,
  ChibiccDumperTypedef,
  ChibiccDumperTypeKind,
  ChibiccDumperTypeOfKind,
  ChibiccDumperVariableObject,
  ChibiccDumperVariableRef,
} from '../../src/index';

const rootDir = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const workspacePrefix = '/workspace/';
const fixtureCache = new Map<string, Promise<ChibiccDumperFullDumpResult>>();
let tokensOnlyResultPromise: Promise<ChibiccDumperTokensOnlyResult> | undefined;
let astOnlyResultPromise: Promise<ChibiccDumperAstOnlyResult> | undefined;
let fullResultPromise: Promise<ChibiccDumperFullDumpResult> | undefined;

interface InlineFixture {
  readonly inputPath: string;
  readonly source: string;
}

type FixtureReference = string | InlineFixture;

const boolFixture: InlineFixture = {
  inputPath: 'types/bool.c',
  source: '_Bool value;\n',
};

const shortFixture: InlineFixture = {
  inputPath: 'types/short.c',
  source: 'short value;\n',
};

const enumFixture: InlineFixture = {
  inputPath: 'types/enum.c',
  source: 'enum Value { VALUE_A }; enum Value value;\n',
};

const unionFixture: InlineFixture = {
  inputPath: 'types/union.c',
  source: 'union Value { int a; short b; }; union Value value;\n',
};

const forFixture: InlineFixture = {
  inputPath: 'types/for.c',
  source:
    'int main(void) { for (int i = 0; i < 1; i = i + 1) { } return 0; }\n',
};

const doFixture: InlineFixture = {
  inputPath: 'types/do.c',
  source:
    'int main(void) { int i = 0; do { i = i + 1; } while (i < 1); return i; }\n',
};

const compareAndSwapFixture: InlineFixture = {
  inputPath: 'types/cas.c',
  source:
    'int main(void) { int value = 0; int old = 0; __builtin_compare_and_swap(&value, &old, 1); return 0; }\n',
};

const exchangeFixture: InlineFixture = {
  inputPath: 'types/exchange.c',
  source:
    'int main(void) { int value = 0; __builtin_atomic_exchange(&value, 1); return value; }\n',
};

const tokenFixturePaths: Record<
  Exclude<ChibiccDumperTokenKind, 'TK_KEYWORD'>,
  FixtureReference
> = {
  TK_IDENT: 'test/alignof.c',
  TK_PUNCT: 'test/alignof.c',
  TK_STR: 'test/alignof.c',
  TK_NUM: 'test/complit.c',
  TK_PP_NUM: 'test/alignof.c',
  TK_COMMENT: 'test/comments.c',
  TK_EOF: 'test/alignof.c',
};

const typeFixturePaths: Record<ChibiccDumperTypeKind, FixtureReference> = {
  TY_VOID: 'test/alignof.c',
  TY_BOOL: boolFixture,
  TY_CHAR: 'test/alignof.c',
  TY_SHORT: shortFixture,
  TY_INT: 'test/alignof.c',
  TY_LONG: 'test/alignof.c',
  TY_FLOAT: 'test/cast.c',
  TY_DOUBLE: 'test/arith.c',
  TY_LDOUBLE: 'test/arith.c',
  TY_ENUM: enumFixture,
  TY_PTR: 'test/alignof.c',
  TY_FUNC: 'test/alignof.c',
  TY_ARRAY: 'test/alignof.c',
  TY_VLA: 'test/constexpr.c',
  TY_STRUCT: 'test/alignof.c',
  TY_UNION: unionFixture,
};

const nodeFixturePaths: Record<ChibiccDumperNodeKind, FixtureReference> = {
  ND_NULL_EXPR: 'test/alignof.c',
  ND_ADD: 'test/alloca.c',
  ND_SUB: 'test/alignof.c',
  ND_MUL: 'test/alloca.c',
  ND_DIV: 'test/alignof.c',
  ND_NEG: 'test/arith.c',
  ND_MOD: 'test/alignof.c',
  ND_BITAND: 'test/arith.c',
  ND_BITOR: 'test/arith.c',
  ND_BITXOR: 'test/arith.c',
  ND_SHL: 'test/alignof.c',
  ND_SHR: 'test/alignof.c',
  ND_EQ: 'test/arith.c',
  ND_NE: 'test/arith.c',
  ND_LT: 'test/arith.c',
  ND_LE: 'test/arith.c',
  ND_ASSIGN: 'test/alloca.c',
  ND_COND: 'test/arith.c',
  ND_COMMA: 'test/alignof.c',
  ND_MEMBER: 'test/alignof.c',
  ND_ADDR: 'test/alignof.c',
  ND_DEREF: 'test/alloca.c',
  ND_NOT: 'test/arith.c',
  ND_BITNOT: 'test/arith.c',
  ND_LOGAND: 'test/control.c',
  ND_LOGOR: 'test/control.c',
  ND_RETURN: 'test/alignof.c',
  ND_IF: 'test/control.c',
  ND_FOR: forFixture,
  ND_DO: doFixture,
  ND_SWITCH: 'test/constexpr.c',
  ND_CASE: 'test/constexpr.c',
  ND_BLOCK: 'test/alignof.c',
  ND_GOTO: 'test/control.c',
  ND_GOTO_EXPR: 'test/control.c',
  ND_LABEL: 'test/control.c',
  ND_LABEL_VAL: 'test/control.c',
  ND_FUNCALL: 'test/alignof.c',
  ND_EXPR_STMT: 'test/alignof.c',
  ND_STMT_EXPR: 'test/alignof.c',
  ND_VAR: 'test/alignof.c',
  ND_VLA_PTR: 'test/constexpr.c',
  ND_NUM: 'test/alignof.c',
  ND_CAST: 'test/alignof.c',
  ND_MEMZERO: 'test/alloca.c',
  ND_ASM: 'test/asm.c',
  ND_CAS: compareAndSwapFixture,
  ND_EXCH: exchangeFixture,
};

const keywordToken: ChibiccDumperKeywordToken = {
  kind: 'TK_KEYWORD',
  lexeme: 'return',
  file: 'synthetic.c',
  line: 1,
  atBol: false,
  hasSpace: true,
};

const resolveHostPath = (virtualPath: string): string | undefined => {
  if (!virtualPath.startsWith(workspacePrefix)) {
    return undefined;
  }

  return resolve(rootDir, virtualPath.slice(workspacePrefix.length));
};

const createFilesystemFixtureDump = async (
  relativePath: string
): Promise<ChibiccDumperFullDumpResult> => {
  const absolutePath = resolve(rootDir, relativePath);

  return await dump<ChibiccDumperFullDumpResult>({
    inputPath: relativePath,
    source: readFileSync(absolutePath, 'utf8'),
    includePaths: ['test'],
    dumpTokens: true,
    dumpAst: true,
    host: {
      readFile: (virtualPath: string) => {
        const hostPath = resolveHostPath(virtualPath);
        if (!hostPath || !existsSync(hostPath)) {
          return undefined;
        }
        return readFileSync(hostPath, 'utf8');
      },
      getFileTimestamp: (virtualPath: string) => {
        const hostPath = resolveHostPath(virtualPath);
        if (!hostPath || !existsSync(hostPath)) {
          return undefined;
        }
        return Math.floor(statSync(hostPath).mtimeMs / 1000);
      },
    },
  });
};

const createInlineFixtureDump = async (
  fixture: InlineFixture
): Promise<ChibiccDumperFullDumpResult> =>
  await dump<ChibiccDumperFullDumpResult>({
    inputPath: fixture.inputPath,
    source: fixture.source,
    dumpTokens: true,
    dumpAst: true,
  });

const getFixtureDump = async (
  fixture: FixtureReference
): Promise<ChibiccDumperFullDumpResult> => {
  const key = typeof fixture === 'string' ? fixture : fixture.inputPath;
  let promise = fixtureCache.get(key);
  if (!promise) {
    promise =
      typeof fixture === 'string'
        ? createFilesystemFixtureDump(fixture)
        : createInlineFixtureDump(fixture);
    fixtureCache.set(key, promise);
  }
  return await promise;
};

const visitNode = (
  node: ChibiccDumperNode | undefined,
  visitor: (candidate: ChibiccDumperNode) => boolean
): boolean => {
  if (!node) {
    return false;
  }

  if (visitor(node)) {
    return true;
  }

  const singleChildren: readonly (ChibiccDumperNode | undefined)[] = [
    'lhs' in node ? node.lhs : undefined,
    'rhs' in node ? node.rhs : undefined,
    'cond' in node ? node.cond : undefined,
    'then' in node ? node.then : undefined,
    'else' in node ? node.else : undefined,
    'init' in node ? node.init : undefined,
    'inc' in node ? node.inc : undefined,
    'casAddr' in node ? node.casAddr : undefined,
    'casOld' in node ? node.casOld : undefined,
    'casNew' in node ? node.casNew : undefined,
  ];

  for (const child of singleChildren) {
    if (child && visitNode(child, visitor)) {
      return true;
    }
  }

  const arrayChildren: readonly (readonly ChibiccDumperNode[] | undefined)[] = [
    'body' in node && Array.isArray(node.body) ? node.body : undefined,
    'args' in node ? node.args : undefined,
  ];

  for (const children of arrayChildren) {
    if (children?.some((child) => visitNode(child, visitor))) {
      return true;
    }
  }

  return false;
};

const findNode = <K extends ChibiccDumperNodeKind>(
  result: ChibiccDumperFullDumpResult,
  kind: K
): ChibiccDumperNodeOfKind<K> => {
  let match: ChibiccDumperNode | undefined;

  for (const global of result.ast.globals) {
    if (
      global.isFunction &&
      visitNode(global.body, (candidate) => {
        if (candidate.kind === kind) {
          match = candidate;
          return true;
        }
        return false;
      })
    ) {
      break;
    }
  }

  for (const type of result.types) {
    if (match) {
      break;
    }
    if (
      'vlaLen' in type &&
      visitNode(type.vlaLen, (candidate) => {
        if (candidate.kind === kind) {
          match = candidate;
          return true;
        }
        return false;
      })
    ) {
      break;
    }
  }

  if (!match) {
    throw new Error(`Node kind ${kind} was not found in the fixture dump.`);
  }

  return match as ChibiccDumperNodeOfKind<K>;
};

export const getTokenByKind = async <K extends ChibiccDumperTokenKind>(
  kind: K
): Promise<ChibiccDumperTokenOfKind<K>> => {
  if (kind === 'TK_KEYWORD') {
    return keywordToken as ChibiccDumperTokenOfKind<K>;
  }

  const result = await getFixtureDump(
    tokenFixturePaths[kind as Exclude<ChibiccDumperTokenKind, 'TK_KEYWORD'>]
  );
  const token = result.tokens.find(
    (candidate): candidate is ChibiccDumperTokenOfKind<K> =>
      candidate.kind === kind
  );

  if (!token) {
    throw new Error(`Token kind ${kind} was not found in the fixture dump.`);
  }

  return token;
};

export const getTypeByKind = async <K extends ChibiccDumperTypeKind>(
  kind: K
): Promise<ChibiccDumperTypeOfKind<K>> => {
  const result = await getFixtureDump(typeFixturePaths[kind]);
  const dumpedType = result.types.find(
    (candidate): candidate is ChibiccDumperTypeOfKind<K> =>
      candidate.kind === kind
  );

  if (!dumpedType) {
    throw new Error(`Type kind ${kind} was not found in the fixture dump.`);
  }

  return dumpedType;
};

export const getNodeByKind = async <K extends ChibiccDumperNodeKind>(
  kind: K
): Promise<ChibiccDumperNodeOfKind<K>> =>
  findNode(await getFixtureDump(nodeFixturePaths[kind]), kind);

export const getHeaderComment =
  async (): Promise<ChibiccDumperHeaderComment> => {
    const result = await getFixtureDump('test/comments.c');
    const comment = result.ast.globals.flatMap(
      (globalObject) => globalObject.headerComments ?? []
    )[0];

    if (!comment) {
      throw new Error('No header comment was found in comments.c.');
    }

    return comment;
  };

export const getTokenRef = async (): Promise<ChibiccDumperTokenRef> => {
  const comment = await getHeaderComment();
  return comment.tokens[0];
};

export const getVariableRef = async (): Promise<ChibiccDumperVariableRef> => {
  const node = await getNodeByKind('ND_VAR');
  return node.var;
};

export const getMember = async (): Promise<ChibiccDumperMember> => {
  const dumpedType = await getTypeByKind('TY_STRUCT');
  const member = dumpedType.members[0];

  if (!member) {
    throw new Error('No struct member was found in the fixture dump.');
  }

  return member;
};

export const getScope = async (): Promise<ChibiccDumperScope> => {
  const result = await getFixtureDump('test/alignof.c');
  return result.scopes[0];
};

export const getTag = async (): Promise<ChibiccDumperTag> => {
  const result = await getFixtureDump('test/struct.c');
  return result.tags[0];
};

export const getTypedef = async (): Promise<ChibiccDumperTypedef> => {
  const result = await getFixtureDump('test/typedef.c');
  return result.typedefs[0];
};

export const getLocalObject = async (): Promise<ChibiccDumperLocalObject> => {
  const result = await getFixtureDump('test/comments.c');
  const functionObject = result.ast.globals.find(
    (candidate): candidate is ChibiccDumperFunctionObject =>
      candidate.isFunction
  );
  const localObject = functionObject?.locals[0] ?? functionObject?.params[0];

  if (!localObject) {
    throw new Error('No local object was found in comments.c.');
  }

  return localObject;
};

export const getVariableObject =
  async (): Promise<ChibiccDumperVariableObject> => {
    const result = await getFixtureDump('test/comments.c');
    const object = result.ast.globals.find(
      (candidate): candidate is ChibiccDumperVariableObject =>
        !candidate.isFunction
    );

    if (!object) {
      throw new Error('No variable object was found in comments.c.');
    }

    return object;
  };

export const getFunctionObject =
  async (): Promise<ChibiccDumperFunctionObject> => {
    const result = await getFixtureDump('test/comments.c');
    const object = result.ast.globals.find(
      (candidate): candidate is ChibiccDumperFunctionObject =>
        candidate.isFunction
    );

    if (!object) {
      throw new Error('No function object was found in comments.c.');
    }

    return object;
  };

export const getProgram = async (): Promise<ChibiccDumperProgram> =>
  (await getFixtureDump('test/comments.c')).ast;

export const getRelocation = async (): Promise<ChibiccDumperRelocation> => {
  const result = await getFixtureDump('test/control.c');
  const relocation = result.ast.globals.flatMap((globalObject) =>
    globalObject.isFunction ? [] : (globalObject.relocations ?? [])
  )[0];

  if (!relocation) {
    throw new Error('No relocation was found in control.c.');
  }

  return relocation;
};

export const getObject = async (): Promise<ChibiccDumperObject> =>
  (await getFixtureDump('test/comments.c')).ast.globals[0];

const getTokensOnlyResultPromise =
  (): Promise<ChibiccDumperTokensOnlyResult> => {
    if (!tokensOnlyResultPromise) {
      tokensOnlyResultPromise = dump<ChibiccDumperTokensOnlyResult>({
        inputPath: 'types/tokens-only.c',
        source: 'int main(void) { return 0; }\n',
        dumpTokens: true,
        dumpAst: false,
      });
    }
    return tokensOnlyResultPromise!;
  };

const getAstOnlyResultPromise = (): Promise<ChibiccDumperAstOnlyResult> => {
  if (!astOnlyResultPromise) {
    astOnlyResultPromise = dump<ChibiccDumperAstOnlyResult>({
      inputPath: 'types/ast-only.c',
      source: 'int global;\nint main(void) { return global; }\n',
      dumpTokens: false,
      dumpAst: true,
    });
  }
  return astOnlyResultPromise!;
};

const getFullResultPromise = (): Promise<ChibiccDumperFullDumpResult> => {
  if (!fullResultPromise) {
    fullResultPromise = dump<ChibiccDumperFullDumpResult>({
      inputPath: 'types/full.c',
      source: 'int global;\nint main(void) { return global + 1; }\n',
      dumpTokens: true,
      dumpAst: true,
    });
  }
  return fullResultPromise!;
};

export const getTokensOnlyResult =
  async (): Promise<ChibiccDumperTokensOnlyResult> =>
    await getTokensOnlyResultPromise();

export const getAstOnlyResult = async (): Promise<ChibiccDumperAstOnlyResult> =>
  await getAstOnlyResultPromise();

export const getFullResult = async (): Promise<ChibiccDumperFullDumpResult> =>
  await getFullResultPromise();

export const getDumpResult = async (): Promise<ChibiccDumperDumpResult> =>
  await getFullResultPromise();

export const defineTokenKindTest = <K extends ChibiccDumperTokenKind>(
  kind: K,
  assertToken: (token: ChibiccDumperTokenOfKind<K>) => void | Promise<void>
): void => {
  test(`${kind} exposes the corresponding token interface`, async () => {
    await assertToken(await getTokenByKind(kind));
  });
};

export const defineTypeKindTest = <K extends ChibiccDumperTypeKind>(
  kind: K,
  assertType: (dumpedType: ChibiccDumperTypeOfKind<K>) => void | Promise<void>
): void => {
  test(`${kind} exposes the corresponding type interface`, async () => {
    await assertType(await getTypeByKind(kind));
  });
};

export const defineNodeKindTest = <K extends ChibiccDumperNodeKind>(
  kind: K,
  assertNode: (node: ChibiccDumperNodeOfKind<K>) => void | Promise<void>
): void => {
  test(`${kind} exposes the corresponding node interface`, async () => {
    await assertNode(await getNodeByKind(kind));
  });
};
